### ISSUE TITLE
option for sqare images

### ISSUE THREAD

**Issue by pascalwacker** [thoughtbot/baccano#36]
First of all, let me tell you how neat this project is! For some usecases it would however be great to generate square instead of circular images.

Sadly I've never worked on a ruby project (plus have upcoming exams, so very little time right now ;)), therefore I'd need some advice on how to implement it.

I guess the most simple fix would be to add lines 2-4 in the https://github.com/thoughtbot/baccano/blob/master/views/index.erb file using ruby (something like `<%= @avatar.clip %>` and set the default value for it to `<clipPath id="clip"><circle cx="100" cy="100" r="100"/></clipPath>`). Would you also choose this approach? Then there could be an optional get parameter `?shape=circle|square` with fallback to circle if it's not square.

What do you think?

**Comment by tysongach** [comment]
Hi - thanks for opening this issue. Unfortunately, we’ve decided to deprecate this project. It will be fully shut down on July 1, 2020.
